// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKVSVdFe0wa73uLX5bpoel0o8p3m3MGMU',
    appId: '1:118087044551:web:cf6c25ea0dadd3a4df5de2',
    messagingSenderId: '118087044551',
    projectId: 'my-travel-buddy-d0689',
    authDomain: 'my-travel-buddy-d0689.firebaseapp.com',
    storageBucket: 'my-travel-buddy-d0689.appspot.com',
    measurementId: 'G-WZMKJJW1ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjMxsR6lmC6urG0JxOXoglL50p-uh2UGQ',
    appId: '1:118087044551:android:f6448fc11543bce4df5de2',
    messagingSenderId: '118087044551',
    projectId: 'my-travel-buddy-d0689',
    storageBucket: 'my-travel-buddy-d0689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2n_m0GyiDvl9Fd1BClKhmBMZW36z15NQ',
    appId: '1:118087044551:ios:b7080b3de1c49ad7df5de2',
    messagingSenderId: '118087044551',
    projectId: 'my-travel-buddy-d0689',
    storageBucket: 'my-travel-buddy-d0689.appspot.com',
    iosClientId: '118087044551-cuduv0fdqtnrc7pf38a49n7l0i8i2u30.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2n_m0GyiDvl9Fd1BClKhmBMZW36z15NQ',
    appId: '1:118087044551:ios:b7080b3de1c49ad7df5de2',
    messagingSenderId: '118087044551',
    projectId: 'my-travel-buddy-d0689',
    storageBucket: 'my-travel-buddy-d0689.appspot.com',
    iosClientId: '118087044551-cuduv0fdqtnrc7pf38a49n7l0i8i2u30.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelBuddy',
  );
}
